[project]
name = "mock-dss-load-tests-taurus"
version = "0.1.0"
description = "Load testing for digital signature service using Taurus, simulating real-world usage and performance scenarios."
readme = "README.md"
requires-python = "==3.8.10"
dependencies = [
    "bzt>=1.16.42",
]
